//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEY_CustomersTherapists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KEY_CustomersTherapists()
        {
            this.TblSession = new HashSet<TblSession>();
        }
    
        public string ID { get; set; }
        public string therapistID { get; set; }
        public string customerID { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblTherapist TblTherapist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSession { get; set; }
    }
}
