//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEY_Purchases
    {
        public int purchaseID { get; set; }
        public string customerID { get; set; }
        public string userID { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblPurchase TblPurchase { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
