//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomer()
        {
            this.KEY_CustomersTherapists = new HashSet<KEY_CustomersTherapists>();
            this.KEY_Purchases = new HashSet<KEY_Purchases>();
            this.TblPhone = new HashSet<TblPhone>();
        }
    
        public string ID { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<int> houseNum { get; set; }
        public string zipCode { get; set; }
        public Nullable<byte> gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_CustomersTherapists> KEY_CustomersTherapists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_Purchases> KEY_Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPhone> TblPhone { get; set; }
    }
}
