//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPurchase()
        {
            this.KEY_PurchaseItems = new HashSet<KEY_PurchaseItems>();
            this.KEY_Purchases = new HashSet<KEY_Purchases>();
        }
    
        public int ID { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public Nullable<int> tool { get; set; }
        public string peymentNum { get; set; }
        public Nullable<double> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_PurchaseItems> KEY_PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_Purchases> KEY_Purchases { get; set; }
    }
}
