//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSession
    {
        public int ID { get; set; }
        public int sessionNumber { get; set; }
        public System.DateTime sessionDate { get; set; }
        public Nullable<int> duration { get; set; }
        public string description { get; set; }
        public string comments { get; set; }
        public string conclustions { get; set; }
        public string keyID { get; set; }
    
        public virtual KEY_CustomersTherapists KEY_CustomersTherapists { get; set; }
    }
}
