//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubscription
    {
        public int itemID { get; set; }
        public int subID { get; set; }
        public System.DateTime finishDate { get; set; }
        public Nullable<double> monthlyPrice { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual TblItem TblItem { get; set; }
    }
}
