//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTherapist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTherapist()
        {
            this.KEY_CustomersTherapists = new HashSet<KEY_CustomersTherapists>();
        }
    
        public string therapistID { get; set; }
        public string clinicAddress { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public Nullable<byte> clinicType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEY_CustomersTherapists> KEY_CustomersTherapists { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
